sudo: required

services:
  - docker

script: |
    docker-compose down &&
    docker-compose up --abort-on-container-exit build &&
    docker-compose up --abort-on-container-exit upload-archives

#branches:
#  only:
#  - master
#
