language: java
sudo: required

before_install:
  # decrypting gpg key
  - openssl aes-256-cbc -d -k ${ENCRYPTION_KEY} -in files/deployment/.gnupg/secring.gpg -out $HOME/.gnupg/secring.gpg

script: >
  ./gradlew build uploadArchives -PossrhUsername=mageddo -PossrhPassword=${SIGNING_PASSWORD} \
  -Psigning.password=${SIGNING_PASSWORD} -Psigning.keyId=${SIGNING_KEY_ID} \
  -Psigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg

#branches:
#  only:
#  - master
#
