version: '3'
services:
  travis-build:
    image: openjdk:11-jdk
    command: ./builder.sh deploy
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root
    environment:
      - CURRENT_BRANCH=$TRAVIS_BRANCH # current branch name

  travis-pull-request-build:
    image: openjdk:11-jdk
    command: ./gradlew build
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root
