version: '3'
services:
  travis-build:
    image: openjdk:11-jdk
    command: |
      sh -c '

      '
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root

  travis-pull-request-build:
    image: openjdk:11-jdk
    command: ./gradlew build
    working_dir: /app
    volumes:
      - ./:/app
      - $HOME:/root
