CREATE TABLE USER_PARAMETER ( 
	IDT_USER_PARAMETER INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 CYCLE) PRIMARY KEY, 
	IDT_PARAMETER INTEGER NOT NULL, 
	COD_USER VARCHAR(255) NOT NULL, 
	VAL_PARAMETER VARCHAR(1000), 
	DAT_CREATION TIMESTAMP NOT NULL, 
	DAT_UPDATE TIMESTAMP NOT NULL, 
	UNIQUE(IDT_PARAMETER, COD_USER) 
);

CREATE TABLE PARAMETER( 
	IDT_PARAMETER INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 CYCLE) PRIMARY KEY, 
	NAM_PARAMETER VARCHAR(255) NOT NULL, 
	VAL_PARAMETER VARCHAR(1000), 
	DAT_CREATION TIMESTAMP NOT NULL, 
	DAT_UPDATE TIMESTAMP NOT NULL, 
	UNIQUE(NAM_PARAMETER) 
); 
